learning/urls.py
from django.urls import path
from . import views

'''appname='learning'''''
urlpatterns=[
    path('', views.index, name='index'),
    path('data',views.data, name='data'),
    path('detail/<int:id>', views.cours_detail, name='cours_detail'),
    path('accounts/signup', views.signup ,name='signup'),
    path('accounts/profile', views.profile ,name='profile'),
    path('cours/<int:id>/edite', views.edit_cours,name='edit_cours'),
    path('section/<int:section_id>/edite', views.page,name='dashboard_cours'),



    path('live', views.live, name='live'),
    path('get_stream', views.get_stream, name='get_stream'),
    path('server', views.server, name='server'),
    path('live/<str:room_name>/', views.room, name='room'),
    path('webrtc', views.webrtc, name='webrtc')
]

onlinelearning/urls.py
from django.contrib import admin
from django.urls import include, path

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('learning.urls')),
    path('admin/', admin.site.urls),
    path('accounts/',include('django.contrib.auth.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

learning/models.py
from django.db import models
from django.contrib.auth.models import User
import json
# Create your models here.

class Cours(models.Model):
    title = models.CharField(max_length=50)
    free = models.IntegerField()
    available_seats = models.IntegerField()
    _schedule = models.CharField(max_length=100, db_column='schedule')
    picture = models.ImageField(upload_to='cours', default='default.jpg')
    objectives = models.TextField()
    eligibility = models.TextField()
    trainer = models.ForeignKey(User, on_delete=models.CASCADE, null = True, related_name='cours')


    @property
    def schedule(self):
        s = json.loads(self._schedule)
        return f'{s[0]}.00 pm to {s[1]}.00 pm'


class Sections(models.Model):
    title = models.CharField(max_length=50)
    detail = models.TextField()
    cour = models.ForeignKey(Cours, on_delete=models.CASCADE)


class Pages(models.Model):
    title = models.CharField(max_length=50)
    content = models.TextField()
    section = models.ForeignKey(Sections, on_delete=models.CASCADE)

class Expoilted(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='exploited')
    type = models.CharField(max_length=50, choices=(('T','Teacher'),('S','Student')))

learning/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.contrib.auth.models import User
from .models import Expoilted, Cours
from django.forms import ModelForm

class SingupForm(UserCreationForm):

    def __init__(self, *args, **kwargs):
        super(SingupForm, self).__init__(*args, **kwargs)

        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'single-input'

    username = forms.CharField(max_length=30, required=False, help_text='Username', widget=forms.TextInput(attrs={'placeholder': "username"}))
    #                            widget=forms.TextInput(attrs = {'class' : 'single-input'}))
    # first_name = forms.CharField(max_length=30, required=False, help_text='First Name')
    # last_name = forms.CharField(max_length=30, required=False, help_text='Last Name')
    email = forms.CharField(max_length=100, required=False, help_text='Email', widget=forms.TextInput(attrs={'placeholder':'E-mail'}))
    password1 = forms.CharField(max_length=100, required=False, help_text='password', widget=forms.PasswordInput(attrs={'placeholder':'Password'}))
    password2 = forms.CharField(max_length=100, required=False, help_text='password', widget=forms.PasswordInput(attrs={'placeholder':'Password'}))

    class Meta:
        model = User
        fields = {'username', 'email', 'password1', 'password2'}



class ExloitedForm(ModelForm):
    # type = forms.MultipleChoiceField(choices=(('T','Teacher'),('S','Student')))
    # type = forms.ModelChoiceField(queryset=Expoilted.objects.all(), to_field_name='type')
    class Meta:
        model = Expoilted
        fields = {'type'}


class CoursForm(ModelForm):
    def __init__(self, *arg, **kwargs):
        super(CoursForm, self).__init__(*arg, **kwargs)

        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'single-input'


    class Meta:
        model = Cours
        fields = '__all__'
        exclude = ['trainer']

learning/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.http import StreamingHttpResponse
from .models import Cours, Sections, Pages, Expoilted
from .forms import SingupForm, ExloitedForm, CoursForm
from django.shortcuts import redirect
from django.contrib.auth.decorators import  login_required
import socket
import cv2
import json
# Create your views here.


def index(request):
    cours = Cours.objects.all()
    return render(request, 'learn/index.html',{'cours':cours})


def data(request):
    section_list = []
    # page_list = []
    # f = open('data.json', 'r')
    # for i in json.load(f):
    #     Cour = Cours(free=i['free'], title=i['title'],
    #                  available_seats=i['available_seats'], schedule=i['schedule'],
    #                  objectives=i['objectives'],eligibility=i['eligibility'])
    #     Cour.save()
    #     for s in i['section']:
    #         section = Sections(title=s['title'], detail=s['detail'], cour=Cour)
    #         section.save()
    #         # section_list.append(s)
    #         for p in s['page']:
    #             Page = Pages(title=p['title'], content=p['content'],
    #                          section=section)
    #             Page.save()
    # return HttpResponse(page_list)
    '''trainer-free-available_seats-schedule-picture-objectives-eligibility'''
        # Cour = Cours(free=i['free'],title=i['title'],
        #              available_seats=i['available_seats'], schedule=i['schedule'],
        #              objectives=i['objectives'],eligibility=i['eligibility'])
        # Cour.save()
        #
        # '''title-detail-cour'''
        # section = Sections(title=i['section'][0]['title'], detail=i['section'][0]['detail'],cour= Cour)
        # section.save()
        #
        # '''title-detail-section'''
        # Page = Pages(title=i['section'][0]['page'][0]['title'], content=i['section'][0]['page'][0]['content'], section= section)
        # Page.save()

    data = Cours.objects.all()

    return HttpResponse(data[0].free)




def cours_detail(request,id):
    cour = Cours.objects.get(id=id)

    # all_section = []
    # return HttpResponse(cour.sections_set.all())

    return render(request,'learn/cours_detail.html', {'cour': cour})



def signup(request):

    form = SingupForm()
    if request.POST:
        form = SingupForm(request.POST)
        print(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/')
    return render(request, 'registration/sign_up.html', {'form': form})



@login_required
def profile(request):
    user = request.user
    expoilted= user.exploited
    print(user.cours.all())
    # expoilted = Expoilted.objects.get(user = user)
    # print(expoilted)
    # user_e = user.expoilted_set.count()
    form = ExloitedForm(instance=expoilted)
    if request.POST:
        form = ExloitedForm(instance=expoilted, data=request.POST)
        if form.is_valid():
            form.save()
            user_e = form.save(commit=False)
            # user_e.user = user
            # user_e.user.add(user)
            # user.Expoilted = user_e

            # user_e.save()
            print('ok')


    return render(request,'registration/profile.html', {'User': request.user, 'form' : form})

@login_required
def edit_cours(request, id):
    cour = Cours.objects.get(id=id)
    form = CoursForm(instance=cour)
    if request.POST:
        form = CoursForm(request.POST, request.FILES, instance=cour)
        if form.is_valid():
            form.save()
            # return render(request, 'learn/dashboard_cours.html', {'form': form, 'cour': cour})
    return render(request, 'learn/edit_cours.html', {'form': form})

def page(request, section_id):
    section = Sections.objects.get(pk = section_id)

    return render(request, 'learn/dashboard_cours.html', {'section': section})


def server(request):
    # cap = cv2.VideoCapture(0)
    #
    # # while(True):
    # ret, frame = cap.read()
    #
    # ret, jpeg = cv2.imencode('.jpg', frame)
    # string = jpeg.tostring()
    # yield (b'--frame\r\n'b'Content-Type: text/plain\r\n\r\n'+string+b'\r\n')

    host = '127.0.0.1'

    port = 8000

    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
        s.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
        s.bind((host,port))
        s.listen(1)

        conn, addr  = s.accept()
        print('s')
        while True:
            # conn.send("stream()")
            conn.send('test')
        s.close()

def get_stream(request):

    host = '127.0.0.1'
    port = 8000

    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
        s.connect((host,port))
        # conn, addr = s.accept()
        while 1:
            print("d")
            d = s.recv(1024)
            print(d)

        s.close()
    return StreamingHttpResponse(get_servcer(),content_type='multipart/x-mixed-replace; boundary=frame')


def live(request):
    # return StreamingHttpResponse(stream(),content_type='multipart/x-mixed-replace; boundary=frame')
    return render(request, 'live/live.html')

def room(request, room_name):
    return render(request, 'live/room.html', {
        'room_name': room_name
    })


def webrtc(request):
    return render(request,'live/webrtc.html')

learning/templates/learn/cours_detail.html
{% extends "main.html" %}
{% load static %}

{% block Content %}
        <!--================Home Banner Area =================-->
    <section class="banner_area">
      <div class="banner_inner d-flex align-items-center">
        <div class="overlay"></div>
        <div class="container">
          <div class="row justify-content-center">
            <div class="col-lg-6">
              <div class="banner_content text-center">
                <h2>Course Details</h2>
                <div class="page_link">
                  <a href="index.html">Home</a>
                  <a href="courses.html">Courses</a>
                  <a href="course-details.html">Courses Details</a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
    <!--================End Home Banner Area =================-->
    <!--================ Start Course Details Area =================-->
    <section class="course_details_area section_gap">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 course_details_left">
                    {% if request.user.id %}
                        <a href="" class="btn btn-primary">Edit</a>
                        <br><br>
                    {% endif %}
                    <div class="main_image">
                        <img class="img-fluid" src="{{ cour.picture.url }}" alt="">
                    </div>
                    <div class="content_wrapper">
                        <h4 class="title">Objectives</h4>
                        <div class="content">
                            {{ cour.objectives }}
                        </div>

                        <h4 class="title">Eligibility</h4>
                        <div class="content">
                            {{ cour.eligibility }}
                        </div>

                        <h4 class="title">Course Outline</h4>
                        <div class="content">
                            <ul class="course_list">
                             {% for section in cour.sections_set.all %}
                                <li class="justify-content-between d-flex">
                                    <p>{{ section.title }}</p>
                                    <a class="primary-btn text-uppercase" href="{{ section.id }}">View Details</a>
                                    <a class="btn btn-primary" href="{% url 'dashboard_cours' section.id %}">Edit</a>
                                </li>
                              {% endfor %}
                            </ul>
                        </div>
                    </div>
                </div>


                <div class="col-lg-4 right-contents">
                    <ul>
                        <li>
                            <a class="justify-content-between d-flex" href="#">
                                <p>Trainer’s Name</p>
                                <span class="or">George Mathews</span>
                            </a>
                        </li>
                        <li>
                            <a class="justify-content-between d-flex" href="#">
                                <p>Course Fee </p>
                                <span>${{ cour.free }}</span>
                            </a>
                        </li>
                        <li>
                            <a class="justify-content-between d-flex" href="#">
                                <p>Available Seats </p>
                                <span>{{ cour.available_seats  }}</span>
                            </a>
                        </li>
                        <li>
                            <a class="justify-content-between d-flex" href="#">
                                <p>Schedule </p>
{#                                <span>2.00 pm to 4.00 pm</span>#}
                                <span>{{ cour.schedule  }}</span>
                            </a>
                        </li>
                    </ul>
                    <a href="#" class="primary-btn2 text-uppercase enroll rounded-0 text-white">Enroll the course</a>

                    <h4 class="title">Reviews</h4>
                    <div class="content">
                        <div class="review-top row pt-40">
                            <div class="col-lg-12">
                                <h6 class="mb-15">Provide Your Rating</h6>
                                <div class="d-flex flex-row reviews justify-content-between">
                                    <span>Quality</span>
                                    <div class="star">
                                        <i class="ti-star checked"></i>
                                        <i class="ti-star checked"></i>
                                        <i class="ti-star checked"></i>
                                        <i class="ti-star"></i>
                                        <i class="ti-star"></i>
                                    </div>
                                    <span>Outstanding</span>
                                </div>
                                <div class="d-flex flex-row reviews justify-content-between">
                                    <span>Puncuality</span>
                                    <div class="star">
                                        <i class="ti-star checked"></i>
                                        <i class="ti-star checked"></i>
                                        <i class="ti-star checked"></i>
                                        <i class="ti-star"></i>
                                        <i class="ti-star"></i>
                                    </div>
                                    <span>Outstanding</span>
                                </div>
                                <div class="d-flex flex-row reviews justify-content-between">
                                    <span>Quality</span>
                                    <div class="star">
                                        <i class="ti-star checked"></i>
                                        <i class="ti-star checked"></i>
                                        <i class="ti-star checked"></i>
                                        <i class="ti-star"></i>
                                        <i class="ti-star"></i>
                                    </div>
                                    <span>Outstanding</span>
                                </div>
                            </div>
                        </div>
                        <div class="feedeback">
                            <h6>Your Feedback</h6>
                            <textarea name="feedback" class="form-control" cols="10" rows="10"></textarea>
                            <div class="mt-10 text-right">
                                <a href="#" class="primary-btn2 text-right rounded-0 text-white">Submit</a>
                            </div>
                        </div>
                        <div class="comments-area mb-30">
                            <div class="comment-list">
                                <div class="single-comment single-reviews justify-content-between d-flex">
                                    <div class="user justify-content-between d-flex">
                                        <div class="thumb">
                                            <img src="img/blog/c1.jpg" alt="">
                                        </div>
                                        <div class="desc">
                                            <h5><a href="#">Emilly Blunt</a>
                                                <div class="star">
                                                    <span class="ti-star checked"></span>
                                                    <span class="ti-star checked"></span>
                                                    <span class="ti-star checked"></span>
                                                    <span class="ti-star"></span>
                                                    <span class="ti-star"></span>
                                                </div>
                                            </h5>
                                            <p class="comment">
                                                Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do
                                                eiusmod tempor incididunt ut labore et dolore.
                                            </p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="comment-list">
                                <div class="single-comment single-reviews justify-content-between d-flex">
                                    <div class="user justify-content-between d-flex">
                                        <div class="thumb">
                                            <img src="img/blog/c2.jpg" alt="">
                                        </div>
                                        <div class="desc">
                                            <h5><a href="#">Elsie Cunningham</a>
                                                <div class="star">
                                                    <span class="ti-star checked"></span>
                                                    <span class="ti-star checked"></span>
                                                    <span class="ti-star checked"></span>
                                                    <span class="ti-star"></span>
                                                    <span class="ti-star"></span>
                                                </div>
                                            </h5>
                                            <p class="comment">
                                                Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do
                                                eiusmod tempor incididunt ut labore et dolore.
                                            </p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="comment-list">
                                <div class="single-comment single-reviews justify-content-between d-flex">
                                    <div class="user justify-content-between d-flex">
                                        <div class="thumb">
                                            <img src="img/blog/c3.jpg" alt="">
                                        </div>
                                        <div class="desc">
                                            <h5><a href="#">Maria Luna</a>
                                                <div class="star">
                                                    <span class="ti-star checked"></span>
                                                    <span class="ti-star checked"></span>
                                                    <span class="ti-star checked"></span>
                                                    <span class="ti-star"></span>
                                                    <span class="ti-star"></span>
                                                </div>
                                            </h5>
                                            <p class="comment">
                                                Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do
                                                eiusmod tempor incididunt ut labore et dolore.
                                            </p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!--================ End Course Details Area =================-->
{% endblock %}

learning/templates/learn/dashboard_cours.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v4.0.1">
    <title>Dashboard Template · Bootstrap</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.5/examples/dashboard/">

    <!-- Bootstrap core CSS -->
<link href="../assets/dist/css/bootstrap.css" rel="stylesheet">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    <!-- Custom styles for this template -->
    <link href="{% static 'dashboard.css' %}" rel="stylesheet">
  </head>
  <body>
    <nav class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow">
  <a class="navbar-brand col-md-3 col-lg-2 mr-0 px-3" href="#">Company name</a>
  <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-toggle="collapse" data-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <input class="form-control form-control-dark w-100" type="text" placeholder="Search" aria-label="Search">
  <ul class="navbar-nav px-3">
    <li class="nav-item text-nowrap">
      <a class="nav-link" href="#">Sign out</a>
    </li>
  </ul>
</nav>

<div class="container-fluid">
  <div class="row">
    <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
      <div class="sidebar-sticky pt-3">

        <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
          <span>Saved reports</span>
          <a class="d-flex align-items-center text-muted add_page_to_section" href="#" aria-label="Add a new report">
            <span data-feather="plus-circle"></span>
          </a>
        </h6>
        <ul class="nav flex-column mb-2 nav_page">
            {% for page in section.pages_set.all %}
                <li class="nav-item">
                    <a class="nav-link" href="#">
                      <span data-feather="file-text"></span>
                        {{ page.title }}
                    </a>
                </li>
            {% endfor %}

          {% comment %}<li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="file-text"></span>
              Current month
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="file-text"></span>
              Last quarter
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="file-text"></span>
              Social engagement
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="file-text"></span>
              Year-end sale
            </a>
          </li>{% endcomment %}
        </ul>
      </div>
    </nav>

    <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-md-4">
      <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Dashboard</h1>
        <div class="btn-toolbar mb-2 mb-md-0">
          <div class="btn-group mr-2">
            <button type="button" class="btn btn-sm btn-outline-secondary">Share</button>
            <button type="button" class="btn btn-sm btn-outline-secondary">Export</button>
          </div>
          <button type="button" class="btn btn-sm btn-outline-secondary dropdown-toggle">
            <span data-feather="calendar"></span>
            This week
          </button>
        </div>
      </div>


    </main>
  </div>
</div>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
      <script>window.jQuery || document.write('<script src="../assets/js/vendor/jquery.slim.min.js"><\/script>')</script>
      <script src="bootstrap.bundle.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/feather-icons/4.9.0/feather.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.3/Chart.min.js"></script>
        <script src="{% static 'js/bootstrap.bundle.js' %}"></script>
        <script src="{% static 'js/dashboard.js' %}"></script>
        <script src="{% static 'js/app.js' %}"></script>
  </body>
</html>

learning/templates/learn/edit_cours.html
{% extends 'main.html' %}

{% block Content %}

    <section class="section_gap">
        <div class="container">
            <form action="" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form }}
                <br>
                <br>
                  <button class="click-btn btn btn-default">
                    <span>Submite</span>
                  </button>
            </form>
        </div>
    </section>
{% endblock %}